# Generated by Django 4.2.2 on 2023-06-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='research_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('descriprion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('research_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.research_topics')),
            ],
        ),
    ]
