# Generated by Django 4.2.2 on 2023-06-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/images/publications')),
            ],
        ),
        migrations.CreateModel(
            name='staff_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('summary', models.FileField(upload_to='media/files/timetable')),
                ('faculty_wise_teaching_slot', models.FileField(upload_to='media/files/timetable')),
                ('faculty_wise_timetable', models.FileField(upload_to='media/files/timetable')),
                ('teaching_assistant_loading', models.FileField(upload_to='media/files/timetable')),
                ('specialization_wise_allocation', models.FileField(upload_to='media/files/timetable')),
            ],
        ),
        migrations.AlterField(
            model_name='faculty_members',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty_members',
            name='image',
            field=models.ImageField(upload_to='media/images/faculty'),
        ),
        migrations.CreateModel(
            name='awards_and_recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.faculty_members')),
            ],
        ),
    ]
