# Generated by Django 4.2.2 on 2023-06-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_publications_staff_members_timetable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='awards_and_recognition',
            new_name='awards_and_recognitions',
        ),
        migrations.RenameModel(
            old_name='timetable',
            new_name='timetables',
        ),
        migrations.RenameField(
            model_name='staff_members',
            old_name='email',
            new_name='email_id',
        ),
    ]
