# Generated by Django 4.2.2 on 2023-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_awards_and_recognition_awards_and_recognitions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('concluded', models.BooleanField(default=False)),
                ('dated_at', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phd_college', models.CharField(max_length=100)),
                ('research_area', models.TextField(blank=True)),
                ('institute_webpage', models.CharField(blank=True, max_length=100)),
                ('personal_website', models.CharField(blank=True, max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='faculty_members')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='research_scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('research_area', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('personal_website', models.CharField(blank=True, max_length=100)),
                ('email_id', models.EmailField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='research_scholars')),
            ],
        ),
        migrations.CreateModel(
            name='socities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=100)),
                ('email_id', models.EmailField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='staff_members')),
            ],
        ),
        migrations.RemoveField(
            model_name='awards_and_recognitions',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='faculty_members',
            name='research_interest',
        ),
        migrations.DeleteModel(
            name='publications',
        ),
        migrations.DeleteModel(
            name='staff_members',
        ),
        migrations.DeleteModel(
            name='timetables',
        ),
        migrations.DeleteModel(
            name='awards_and_recognitions',
        ),
        migrations.DeleteModel(
            name='faculty_members',
        ),
    ]
