# Generated by Django 4.2.2 on 2023-07-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_education_events_faculty_member_gallery_labs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='research_topics',
            new_name='research_area',
        ),
    ]
