# Generated by Django 4.2.2 on 2023-07-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_research_topics_research_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_area',
            old_name='descriprion',
            new_name='description',
        ),
    ]
