# Generated by Django 4.2.2 on 2023-07-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_descriprion_research_area_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
        migrations.RenameModel(
            old_name='labs',
            new_name='lab',
        ),
        migrations.RenameModel(
            old_name='socities',
            new_name='society',
        ),
    ]
