# Generated by Django 4.2.2 on 2023-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_event_dated_at_alter_event_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='faculty_member',
            options={'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='research_area',
            options={'verbose_name': 'Research Area', 'verbose_name_plural': 'Research Areas'},
        ),
        migrations.AlterModelOptions(
            name='research_scholar',
            options={'verbose_name': 'Research Scholar', 'verbose_name_plural': 'Research Scholars'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Society', 'verbose_name_plural': 'Societies'},
        ),
        migrations.AlterModelOptions(
            name='staff_member',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staff_member',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff_member',
            name='lab',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
