# Generated by Django 4.2.2 on 2023-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_staff_member_email_id_staff_member_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_scholar',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='research_scholar',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='research_scholar',
            name='supervisor',
        ),
    ]
